### PR TITLE
Handle no appmap.yml file

### LINKED ISSUE #27: ENOENT error after tool installation
```Run getappmap/install-action@v1
Adding .appmap to .gitignore
Using @appland/appmap release @appland/appmap-v3.99.0 for linux-x64
Installing AppMap tools from https://github.com/getappmap/appmap-js/releases/download/%40appland/appmap-v3.99.0/appmap-linux-x64
AppMap tools are installed at /usr/local/bin/appmap
Error: ENOENT: no such file or directory, open 'appmap.yml'
```

For an example, see [this job](https://github.com/roberthopman/granny/actions/runs/6397387659/job/17365247458).

### PR DESCRIPTION
**Pull request by ahtrotta**
Fixes #27 

This error occurred for most of the Upworkers:

```Run getappmap/install-action@v1
Adding .appmap to .gitignore
Using @appland/appmap release @appland/appmap-v3.99.0 for linux-x64
Installing AppMap tools from https://github.com/getappmap/appmap-js/releases/download/%40appland/appmap-v3.99.0/appmap-linux-x64
AppMap tools are installed at /usr/local/bin/appmap
Error: ENOENT: no such file or directory, open 'appmap.yml'
```

For an example, see [this job](https://github.com/roberthopman/granny/actions/runs/6397387659/job/17365247458).

This was caused because during the workflow for the `analyze-action` [here](https://github.com/getappmap/analyze-action/blob/086d07e41041caa932241a53cdecd7e392c1cc2d/.github/workflows/appmap-analysis.yml#L32), it runs the install action with the flag `install-appmap-library` set to `false`. Since this action is executed in a new container, if the user has not committed the `appmap.yml` file to their repository, then it won't be found in the new container because the appmap library was not installed.

This PR makes it so that if `install-appmap-library` is set to `false` and there is no `appmap.yml`, we assume `tmp/appmap` because it's nearly certain that the user is using our default settings (since they haven't committed `appmap.yml` to their repo). However, if `install-appmap-library` is set to `true` and there is no `appmap.yml`, then we throw an error.

This PR also makes sure that the `appmapConfig` is passed into the installer in case it needs to update the `appmap.yml` file.

### CODE REVIEW

**Comment by kgilpin** [comment]
Thanks Adam. The thing that still confuses me is, if the installer has run successfully, why isn’t there an appmap.yml?

File: src/Installer.ts [hunk 1]
```diff
@@ -96,9 +96,19 @@ export default class Installer {
...
-    let result = appmapConfig.appmap_dir;
+    let appmapConfig: any;
+    try {
+      const appmapConfigData = await readFile('appmap.yml', 'utf8');
+      appmapConfig = load(appmapConfigData);
+    } catch (e) {
+      const err = e as Error;
+      log(
+        LogLevel.Warn,
+        `${err.message}\n\nappmap.yml not found or unreadable`
```
Comment (kgilpin) [inline src/Installer.ts:107]: IMO it should return undefined in this case, right?

Comment (kgilpin) [reply src/Installer.ts:107]: This only seems to be used as a build output. IDK maybe `tmp/appmap` is best since we are moving away from any variability in that setting.

Comment (kgilpin) [reply src/Installer.ts:107]: Having the build output be undefined will probably cause other problems. 

But I am still puzzled how the installer can run and not leave an appmap.yml.

Comment (ahtrotta) [reply src/Installer.ts:107]: If we return `undefined` from `detectAppMapDir` then `verifyAppMapDir` will fail and throw an error, which I don't think we want.

Comment (ahtrotta) [reply src/Installer.ts:107]: Or, if `expectedAppMapDir` is not defined, then the outputs will contain:

```
{
  appmapDir: undefined
}
```

Comment (ahtrotta) [reply src/Installer.ts:107]: If the value of `this.appmapConfig` is falsy, then we won't write the `appmap.yml` file.

**Review by kgilpin — APPROVED** [review]
